# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373

stripe_api_key: sk_test_ld8RLv6UuAENQtLAOEbzQW8A
stripe_publishable_key: pk_test_GT9YyQg5QSGKdDurDCCxpo4h

S3_BUCKET_NAME: myflix-antoineleclercq-s3
AWS_ACCESS_KEY_ID: AKIAJLDB5YDPFSX3W4DA
AWS_SECRET_ACCESS_KEY: 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
AWS_REGION: us-east-1

production:
  stripe_api_key: sk_test_ld8RLv6UuAENQtLAOEbzQW8A
  stripe_publishable_key: pk_test_GT9YyQg5QSGKdDurDCCxpo4h

