development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: Antoine
  password: antwan

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: Antoine
  password: antwan
